# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-20 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20170620_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Phone', models.IntegerField()),
                ('FieldLocation', models.CharField(max_length=30)),
                ('CropAcres', models.IntegerField()),
            ],
        ),
         migrations.DeleteModel(
             name='register_user',
         ),
    ]
