# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-20 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20170620_1541'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register_user',
        ),
        migrations.DeleteModel(
            name='RegistrationForm',
        ),
    ]
